[project]
name = "mtg-proxy-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=12.1.0",
    "pypdf>=6.6.2",
    "reportlab>=4.4.9",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
